import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:sons_memes/app/modules/home/submodules/lista_audios/domain/entities/audio.dart';

const bannerID = 'ca-app-pub-1898798427054986/3785290002';
const intersticialID = 'ca-app-pub-1898798427054986/7968981556';

const labelGeral = 'Sons Memes';

Color randomColor() {
  final colors = [
    Colors.red,
    Colors.blue,
    Colors.green,
    Colors.pink,
    Colors.purple,
    Colors.indigo,
    Colors.lime,
    Colors.orange,
    Colors.teal,
  ];

  return colors[math.Random().nextInt(colors.length)];
}

final List<Audio> listAudios = [
  Audio(
    id: -81,
    name: 'Circo de soled',
    categoria: 'Yoda LoL',
    filePath: 'audios/yoda/circo-soled.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -80,
    name: 'EOQ',
    categoria: 'Yoda LoL',
    filePath: 'audios/yoda/eoq.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -79,
    name: 'FON',
    categoria: 'Yoda LoL',
    filePath: 'audios/yoda/fon.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -78,
    name: 'Iiihrrll',
    categoria: 'Yoda LoL',
    filePath: 'audios/yoda/iihhrrl.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -77,
    name: 'Lago aqui lago ai?',
    categoria: 'Yoda LoL',
    filePath: 'audios/yoda/lago-aqui.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -76,
    name: 'Solado malucooo!',
    categoria: 'Yoda LoL',
    filePath: 'audios/yoda/solado-maluco.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -75,
    name: 'Vamo clan',
    categoria: 'Yoda LoL',
    filePath: 'audios/yoda/vamo-clan.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -74,
    name: 'AAAAAAAAAAAAAAAA',
    categoria: 'Hastad',
    filePath: 'audios/hastad/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -73,
    name: 'Cabalo imundo do caralho',
    categoria: 'Hastad',
    filePath: 'audios/hastad/cabaloimundo.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -72,
    name: 'Ta de briiiinks',
    categoria: 'Hastad',
    filePath: 'audios/hastad/hastad-choro-mp3cut.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -71,
    name: 'Nha',
    categoria: 'Hastad',
    filePath: 'audios/hastad/hastad-nha.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -70,
    name: 'Olha esse gordo filho',
    categoria: 'Hastad',
    filePath: 'audios/hastad/hastad-rage.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -69,
    name: 'Sapo trollando',
    categoria: 'Hastad',
    filePath: 'audios/hastad/hastad-sendo-trollado-ao-vivo-sapo-imundo.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -68,
    name: 'Yoda SOLAAAADO',
    categoria: 'Hastad',
    filePath: 'audios/hastad/mouse-bugado-stream-o5.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -67,
    name: 'Esse cara é bronce',
    categoria: 'Hastad',
    filePath: 'audios/hastad/perma-ban-00_00_03-.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -66,
    name: 'Eu sou ruim',
    categoria: 'Hastad',
    filePath: 'audios/hastad/rage-num-casal-hastad-vayne-god.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -65,
    name: 'To na sua mente menor',
    categoria: 'Jukes',
    filePath: 'audios/jukes/d-e-m-o-n-s-a-i-y-a-n-mp3cut.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -64,
    name: 'Hoje comeremos cu!!',
    categoria: 'Jukes',
    filePath: 'audios/jukes/hoje-comeremos-cu.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -63,
    name: 'Eu não consigo clicar velho',
    categoria: 'Jukes',
    filePath: 'audios/jukes/jukera-nao-consigo-clicar-velho.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -62,
    name: 'Heheh te achei',
    categoria: 'Jukes',
    filePath: 'audios/jukes/jukes-jogando-de-rengar-hehehehe-171719.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -61,
    name: 'YODÃO YODÃO',
    categoria: 'Jukes',
    filePath: 'audios/jukes/jukes-yoda.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -60,
    name: 'Mata ele yoda',
    categoria: 'Jukes',
    filePath: 'audios/jukes/mate-ele-yoda.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -59,
    name: 'O que eu errei?',
    categoria: 'Jukes',
    filePath: 'audios/jukes/o-que-eu-errei-me-fala.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -58,
    name: 'Hiiii você foi solado',
    categoria: 'Jukes',
    filePath: 'audios/jukes/ta-passando-fome-ai-meu-ousado.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -57,
    name: 'TA PORRA MENOR',
    categoria: 'Jukes',
    filePath: 'audios/jukes/ta-porra.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -56,
    name: 'Tu ta aqui de novo menor',
    categoria: 'Jukes',
    filePath: 'audios/jukes/tu-ta-aqui-de-novo.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -55,
    name: 'Oi moa noite',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/oi-moa-noite.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -54,
    name: 'Vira homem porra',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/vira-homem-porra.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -53,
    name: 'Risada de ladrão',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/risada-ladrao.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -52,
    name: 'Desliga esse computador agora',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/desliga-o-computador-agora.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -51,
    name: 'Se quer dar se fala',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/c-quer-dar-se-fala.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -50,
    name: 'Ai qui diliça',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/ai-que-delicia-mickey.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -49,
    name: 'Olha a maconha',
    categoria: 'SMZINHO',
    filePath: 'audios/smzinho/olha-a-maconha.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -48,
    name: 'Awn zé da manga',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/ze-da-manga.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -47,
    name: 'Só um chupinho',
    categoria: 'SMZINHO',
    filePath: 'audios/smzinho/so-um-chupinho.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -46,
    name: 'Deixa eu joga também',
    categoria: 'SMZINHO',
    filePath: 'audios/smzinho/smzinhovocequecomprouomeueoseu.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -45,
    name: 'Bicho é bom mesmo',
    categoria: 'SMZINHO',
    filePath: 'audios/smzinho/smzinhoobichoebommesmo.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -44,
    name: 'Se levanta baiano',
    categoria: 'SMZINHO',
    filePath: 'audios/smzinho/smzinho-se-levanta-baiano.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -43,
    name: 'Meu heroi fuma maconha',
    categoria: 'SMZINHO',
    filePath: 'audios/smzinho/smzinho-meu-heroi-nao-usa-capa.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -42,
    name: 'Comunista',
    categoria: 'SMZINHO',
    filePath: 'audios/smzinho/smzinho-comunista.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -41,
    name: 'Peguei o esquema',
    categoria: 'SMZINHO',
    filePath: 'audios/smzinho/peguei-o-esquema-smzinho.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -40,
    name: 'Eu e você',
    categoria: 'SMZINHO',
    filePath: 'audios/smzinho/euevc.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -39,
    name: 'Va pa uma porra',
    categoria: 'Tiringa',
    filePath: 'audios/tiringa/va-uma-puma.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -38,
    name: 'Vai ti lasca',
    categoria: 'Tiringa',
    filePath: 'audios/tiringa/tiringa-responde-aos-fas.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -37,
    name: 'Me essa peste',
    categoria: 'Tiringa',
    filePath: 'audios/tiringa/me-essa-peste.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -36,
    name: 'Inscreve e mete o dedo',
    categoria: 'Tiringa',
    filePath: 'audios/tiringa/inscreve.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -35,
    name: 'Eita peste',
    categoria: 'Tiringa',
    filePath: 'audios/tiringa/eita-peste.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -34,
    name: 'Ave maria',
    categoria: 'Tiringa',
    filePath: 'audios/tiringa/bobonica.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -33,
    name: 'Windows xp',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/windows-xp.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -32,
    name: 'What dog',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/what-dog-do.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -31,
    name: 'What are you doing',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/what-are-you-doing-in-my-swamp-.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -30,
    name: 'Vamo usa droga desgraça',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/vamos-usar-droga-desgraca.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -29,
    name: 'Uuur minecraft',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/uuur.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -28,
    name: 'HAHAHAHAH',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/risada-americana.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -27,
    name: 'Error',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/error.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -26,
    name: 'Emotional damage',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/emotional-damage-meme.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -25,
    name: 'EA Sports...',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/ea.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -24,
    name: 'Boom',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/boom.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -23,
    name: 'Baby do biruleibe',
    categoria: 'Aleatório',
    filePath: 'audios/aleatorio/baby-baby-do-baby-do-biruleibe-leibe.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -22,
    name: 'Bora muie do bill',
    categoria: 'Bill',
    filePath: 'audios/bil/bora-mulher-do-bill.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -21,
    name: 'Bora mae do bill',
    categoria: 'Bill',
    filePath: 'audios/bil/bora-mae-do-bill.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -20,
    name: 'Bora fi do bill',
    categoria: 'Bill',
    filePath: 'audios/bil/bora-filho-do-bill.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -19,
    name: 'Bora bill!!',
    categoria: 'Bill',
    filePath: 'audios/bil/bora-bill.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -18,
    name: 'Vou te comer',
    categoria: 'Dragon Ball',
    filePath: 'audios/dragon-ball/vou-te-comer_2.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -17,
    name: 'Soco',
    categoria: 'Dragon Ball',
    filePath: 'audios/dragon-ball/soco.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -16,
    name: 'Saiyan 3',
    categoria: 'Dragon Ball',
    filePath: 'audios/dragon-ball/sayjin-3.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -15,
    name: 'Mas que porra',
    categoria: 'Dragon Ball',
    filePath: 'audios/dragon-ball/mas-que-porra.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -14,
    name: 'É mais de 8000',
    categoria: 'Dragon Ball',
    filePath: 'audios/dragon-ball/maisde8000.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -13,
    name: 'Kamehameha',
    categoria: 'Dragon Ball',
    filePath: 'audios/dragon-ball/goku-kamehameha-br.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -12,
    name: 'O miseravel é um gênio',
    categoria: 'Dragon Ball',
    filePath: 'audios/dragon-ball/e-um-genio.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -11,
    name: 'Vem monstro 2',
    categoria: 'Leo Stronda',
    filePath: 'audios/leo_stronda/vem-monstro.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -10,
    name: 'Vem monstro',
    categoria: 'Leo Stronda',
    filePath: 'audios/leo_stronda/vem-monstro-2.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -9,
    name: 'Vem com calma',
    categoria: 'Leo Stronda',
    filePath: 'audios/leo_stronda/vem-com-calma.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -8,
    name: 'Ta ficando feio',
    categoria: 'Leo Stronda',
    filePath: 'audios/leo_stronda/ta-ficando-feio.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -7,
    name: 'Porra',
    categoria: 'Leo Stronda',
    filePath: 'audios/leo_stronda/porra-leo-stronda.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -6,
    name: 'Vai me mateire',
    categoria: 'Kuduro',
    filePath: 'audios/kuduro/vai-me-mateire.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -5,
    name: 'Tudo pelo estilo',
    categoria: 'Kuduro',
    filePath: 'audios/kuduro/tudo-pelo-estilo.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -4,
    name: 'Tecnisca de Multiplicassuium',
    categoria: 'Kuduro',
    filePath: 'audios/kuduro/tecnisca-de-multiplicassuium.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -3,
    name: 'Oskey',
    categoria: 'Kuduro',
    filePath: 'audios/kuduro/oskey.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -2,
    name: 'O prospio Naruaito',
    categoria: 'Kuduro',
    filePath: 'audios/kuduro/o-prospio-naruaito.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
  Audio(
    id: -1,
    name: 'Ai minha vuaida',
    categoria: 'Kuduro',
    filePath: 'audios/kuduro/ai-meu-deus-ai-minha-vuaida.mp3',
    buttonColor: randomColor(),
    assets: true,
    favorito: false,
  ),
];
